### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by PROTIKMNDL** [rom1v/sndcpy#112] opened 2021-01-29 14:49 UTC
D:\scrcpy-win64-v1.16>sndcpy
Waiting for device...
Performing Streamed Install
Success
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.rom1v.sndcpy/.MainActivity }
Press Enter once audio capture is authorized on the device to start playing...
Playing audio...
The system cannot find the path specified.

**Comment by rom1v** [comment] 2021-01-29 15:06
Duplicate of #60.

**Closed by rom1v** 2021-01-29 15:06 UTC
